DROP TABLE TB_FREE CASCADE  CONSTRAINTS;

CREATE TABLE TB_FREE (
  Free_NO NUMBER,
  Free_GB VARCHAR2(15),
  Free_Title VARCHAR2(50) NOT NULL,
  Free_Writer_ID VARCHAR2(30) NOT NULL,
  Free_Content VARCHAR2(2000) NOT NULL,
  Free_File_ONM VARCHAR2(100),
  Free_File_RNM VARCHAR2(100),
  Free_DT DATE DEFAULT SYSDATE,
  Free_Level NUMBER DEFAULT 0,
  Free_Ref NUMBER,
  Free_Reply_Ref NUMBER,
  Free_Reply_SQ NUMBER DEFAULT 0,
  Free_Read_CNT NUMBER DEFAULT 0,
  
  CONSTRAINT PK_FREE PRIMARY KEY (Free_NO),
  CONSTRAINT FK_FREE_WID FOREIGN KEY (Free_Writer_ID) REFERENCES TB_USER ON DELETE SET NULL,
  CONSTRAINT FK_FREE_REF FOREIGN KEY (Free_Ref) REFERENCES TB_FREE ON DELETE CASCADE,
  CONSTRAINT FK_FREE_REPLY_REF FOREIGN KEY (Free_Reply_Ref) REFERENCES TB_FREE ON DELETE CASCADE
);
COMMENT ON TABLE TB_FREE IS '자유게시판 테이블';
COMMENT ON COLUMN TB_FREE.Free_NO IS '자유게시판 번호';
COMMENT ON COLUMN TB_FREE.Free_GB IS '자유게시판 구분';
COMMENT ON COLUMN TB_FREE.Free_Writer_ID IS '자유게시판 작성자 아이디';
COMMENT ON COLUMN TB_FREE.Free_Title IS '자유게시판 제목';
COMMENT ON COLUMN TB_FREE.Free_Content IS '자유게시판 내용';
COMMENT ON COLUMN TB_FREE.Free_DT IS '자유게시판 올린날짜';
COMMENT ON COLUMN TB_FREE.Free_File_ONM IS '원래첨부파일명';
COMMENT ON COLUMN TB_FREE.Free_File_RNM IS '바뀐첨부파일명';
COMMENT ON COLUMN TB_FREE.Free_Level IS '글레벨(0:원글/1:댓글/2:대댓글)';
COMMENT ON COLUMN TB_FREE.Free_Ref IS '참조원글번호(원글:자기번호/댓글:참조원글번호)';
COMMENT ON COLUMN TB_FREE.Free_Reply_Ref IS '참조답글번호(0:원글/1:자기번호/2:참조댓글번호)';
COMMENT ON COLUMN TB_FREE.Free_Reply_SQ IS '답글순번(시퀀스)';
COMMENT ON COLUMN TB_FREE.Free_Read_CNT IS '조회수';

CREATE SEQUENCE SEQ_TB_FREE_NO
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCACHE;

INSERT INTO TB_FREE VALUES(SEQ_TB_FREE_NO.NEXTVAL, '자유게시판', '자유', 'user11', 'FREEBOARD', '아아ㅏ아아아아아아ㅏ', 
NULL, SYSDATE, NULL, NULL, NULL, NULL, 0);

COMMIT;